### ISSUE TITLE
Describe block with empty message does not run

### ISSUE THREAD

**Issue by danger-ranger** [paulcwarren/ginkgo4j#5]
e.g.

```
Describe("", () -> {
    It("stuff", () -> {
        assertThat(true).isTrue();
    });
});  
```
This won't run any tests

**Comment by danger-ranger** [comment]
Not a big deal, it's just unexpected sometimes

**Comment by paulcwarren** [comment]
So, we suspect an empty Describe label?  Will fix soonest.  Thx for the issue.

**Comment by danger-ranger** [comment]
Yeah. It's not exactly a valid use case, but

**Comment by paulcwarren** [comment]
Hey Gavin,
I started having a look at this today.  When I attempt to run that test I get an IllegalArgumentException from the framework.  I just wanted to check a couple of things.  1. you are seeing the same thing and 2. expected behavior from your point of view.  Do you expect this to run (and obviously pass)?  3. what version of junit are you guys using there?

**Comment by danger-ranger** [comment]
1) Still seeing it, screenshots below.
2) I would expect it to run tests whether or not some of the Describe blocks have empty messages. Failing that I would expect an error message instead of just "No tests were found"
3) We're running ginkgo4j 1.0.7, junit 4.12

![screen shot 2017-02-16 at 11 16 49 am](https://cloud.githubusercontent.com/assets/1178694/23029860/da3ce6fa-f439-11e6-895a-71f48ea53d1e.png)
![screen shot 2017-02-16 at 11 16 39 am](https://cloud.githubusercontent.com/assets/1178694/23029859/da2e5e0a-f439-11e6-8184-99f02b097569.png)

**Comment by paulcwarren** [comment]
Fixed.  Will be in 1.0.8
